name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: self-hosteds

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        curl -OLS https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe
        .\wix311.exe /install /quiet /norestart
        $wixToolsetBinPath = ";C:\Program Files (x86)\WiX Toolset v3.11\bin;"
        $env:PATH = $env:PATH + $wixToolsetBinPath
        "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        md build
        cd build
        & "C:/Program Files/CMake/bin/cmake.exe" .. -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}}
        & "C:/Program Files/CMake/bin/cmake.exe" --build . --config ${{env.BUILD_CONFIGURATION}}
        & "C:/Program Files/CMake/bin/cpack.exe" --verbose

    - uses: actions/upload-artifact@v2
      with:
        name: Windows Installer
        path: |
          build/packages/*.*
